### ISSUE TITLE
Question about the dimension of the Box-muller transform

### ISSUE THREAD

**Issue by WBMao** [InhwanBae/NPSN#2]
Hi,

I have a question about the dimension of the Box-muller transform. In my understanding, the Box-muller transform should work on the `number of samples (n)` dimension. However, in the code, it seems that you use the BM tran. on the `number of feature (s)` dimension. See:

https://github.com/InhwanBae/NPSN/blob/97f56cf93472e753377f51b996c7066e4e2e32d2/train_npsn.py#L71-L78

After line 75, `loc` has the shape of `n, batch size, s`.

And the `bull_muller_transform()` here
https://github.com/InhwanBae/NPSN/blob/97f56cf93472e753377f51b996c7066e4e2e32d2/npsn/utils.py#L7-L14
seems to work on the last dimension of the tensor `x`, which is the `s` dimension.

Please let me know if there is anything wrong with my understanding. Many thanks!

**Comment by InhwanBae** [comment]
Hi @WBMao! 

Box-Muller(BM) transform is designed to map from a two-dimensional (`s=2`) vector on uniform distribution to a two-dimensional (`s=2`) vector on standard, bivariate normal distribution. And when the dimension of the vector is greater than 2 (`s>2`), we can expand the BM transform by simply pairing two dimensions and transforming them. Therefore, BM transforms should operate on the `s` dimension and should be independent of the `batch-size` or `N` dimension.


<div align='center'>
  <img src="https://www.algorithm-archive.org/contents/box_muller/res/cartesian_grid_transform.png" width=48%'>
  <img src="https://www.algorithm-archive.org/contents/box_muller/res/cartesian_rand_transform.png" width=48%'>
</div>

<div align='center'>Images retrieved from https://www.algorithm-archive.org/contents/box_muller/box_muller.html</div>

**Comment by WBMao** [comment]
Hi @InhwanBae !

Thanks for your reply and the helpful link!

It seems that I confused the concepts of samples and feature dimensions😂. 

My understanding of the BM transform is that, we get two samples from the one-dimension uniform distribution and transform these two samples to one-dimension norm distribution (which is the standard, **univariate** normal distribution). And back to the this case, the tensor `loc` has the shape of `n, batch-size, s`. To me, we should pair two samples in the `n` dimension and get `n` samples which follow the `s`-dimension normal distribution.

> The Box–Muller transform, by [George Edward Pelham Box](https://en.wikipedia.org/wiki/George_E._P._Box) and [Mervin Edgar Muller](https://en.wikipedia.org/wiki/Mervin_Edgar_Muller),[[1]](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform#cite_note-1) is a [random number sampling](https://en.wikipedia.org/wiki/Random_number_sampling) method for generating pairs of [independent](https://en.wikipedia.org/wiki/Statistical_independence), standard, [normally distributed](https://en.wikipedia.org/wiki/Normal_distribution) (zero [expectation](https://en.wikipedia.org/wiki/Expected_value), unit [variance](https://en.wikipedia.org/wiki/Variance)) random numbers, given a source of [uniformly distributed](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous)) random numbers.           --from Wiki

**Comment by InhwanBae** [comment]
Hi @WBMao! 

The BM transform must be applied to the pair of random numbers, not random vectors. As a simple example, we should be able to transform the random vector using BM transform even if there is only one random vector. And, if two random vectors are independent, they must be independent even after conversion. I understand it can be confusing enough because the word '*sampling*' in our paper and wiki are applied at different levels (*random latent vector-level* and *random number-level* respectively). Hope this helps you!

**Comment by WBMao** [comment]
Hi @InhwanBae!

Thanks for you explanation! And I have no more questions now.

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions.
