### ISSUE TITLE
Box-Muller

### ISSUE THREAD

**Issue by yk112233** [InhwanBae/NPSN#3]
Thanks for your great work!
But I am confused about the Box-Muller transformation. I know how to do it, but i want to know why we should do it. I'll appreciate it if you could give me an answer.

**Comment by InhwanBae** [comment]
Hi @yk112233!

The main reason for using the Box-Muller transform is that NPSN's discrepancy loss is designed to operate in uniform distribution, while many baseline networks require a random latent vector in the normal distribution. If the baseline network performs the sampling process in uniform distribution, there is no need to use BM transform.

As a simple example, Social-GAN allows the [user to select the sampling space of the latent vector](https://github.com/agrimgupta92/sgan/blob/master/sgan/models.py#L20-L25). Here, BM transform is required when *noise_type* is *gaussian*, but not when it is *uniform*. Hope this helps you!

**Comment by yk112233** [comment]
Thanks for your kind explanation! I got it!
